kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: [USER-EDITOR]
  namespace: [NAMESPACE]
subjects:
- kind: User
  name: [USERNAME_EMAIL]
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: [NAMESPACE]-owner
  apiGroup: rbac.authorization.k8s.io
